### ISSUE TITLE
alias are lost during tile.yml to product/metadata/*.yml generation

### ISSUE THREAD

**Issue by alexvasseur** [cf-platform-eng/tile-generator#186] opened 2017-05-22 22:50 UTC
I am trying to use alias with & and * similar to what is in this file https://concourse.ci/deploying-concourse.html
like this tile.yml
```
...
      postgresql_database: &atc_db atc
...
    properties:
      databases:
      - name: *atc_db
        # make up a role and password
        role: admin
        password: x
```

but the & and * are dropped from the resulting yml in product/metadata as below

This results in bosh deploy failure as no db jobs gets configured and started into the db/0 instance.

```
- name: web
  manifest: |
    postgresql_database: atc
...
- name: db
  manifest: |
    databases:
    - name: atc_db
      password: x
      role: admin
```

Would there be some way to fix this or what do you propose?

**Comment by mboldt** [comment] 2017-06-08 20:21
Hmm, I was unable to reproduce this (i.e., I put a yaml anchor between two properties and they seemed to render appropriately). Could you please send a small, complete example, or some more context (e.g., fill in the `...`s above so I can see where these things are defined) so I can reproduce this?

**Comment by alexvasseur** [comment] 2017-06-09 22:27
Here it is - if I extracted correctly from my github history
The key point is that the `&`gets removed and then don't show up in the final generated manifest by opsman which then breaks the bosh deploy

fyi I have now get rid of this and changed for bosh links but this might impact others tile author who relies on yaml alias 
(as fyi many of the Concourse yml example are using these yaml alias - even the official doc last time I checked)

```
---
name: alex-concourse
icon_file: resources/icon.png
label: Standalone Concourse
description: Standalone Concourse for Platform Automation
packages:
- name: concourse
  type: bosh-release
  path: https://bosh.io/d/github.com/concourse/concourse?v=3.0.1
  #path: release/concourse/concourse-3.0.1.tgz
  version: 3.0.1
- name: garden-runc
  type: bosh-release
  path: https://bosh.io/d/github.com/cloudfoundry-incubator/garden-runc-release?v=1.0.0
  #path: release/garden-runc/garden-runc-1.0.0.tgz
  version: 1.0.0
- name: routing
  type: bosh-release
  path: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.154.0
  #path: release/routing/routing-0.154.0.tgz
  version: 0.154.0
jobs:
- name: web
  label: Concourse frontend
  templates:
  - name: atc
    release: concourse
  - name: tsa
    release: concourse
  - name: route_registrar
    release: routing
  memory: 4096
  ephemeral_disk: 8192
  cpu: 1
  static_ip: 1
  dynamic_ip: 0
  single_az_only: false
  singleton: false
  instances: 1
  properties:
    #---- atc
    # replace with your CI's externally reachable URL, e.g. https://ci.foo.com
    external_url: https://concourse.domain.TODO
    # replace with username/password, or configure GitHub auth
    basic_auth_username: admin
    basic_auth_password: password
    # replace with your SSL cert and key, else automatically generated
    # tls_cert: REPLACE_ME
    # tls_key: REPLACE_ME
    tls_bind_port: 443
    postgresql_database: &atc_db atc
    #---- end of atc
    #---- route_registrar
    nats:
      machines: (( .nats.ips ))
      password: (( .nats.credentials.password ))
      port: 4222
      user: (( .nats.credentials.identity ))
    route_registrar:
      routes:
        - name: concourse
          port: 443
          uris:
            - concourse.(( .cloud_controller.system_domain.value ))
          registration_interval: 20s
          tags: alex-concourse
- name: db
  label: PostgreSQL
  templates:
  - name: postgresql
    release: concourse
  memory: 4096
  ephemeral_disk: 8192
  persistent_disk: 32768
  cpu: 2
  static_ip: 0
  dynamic_ip: 1
  single_az_only: true
  singleton: true
  instances: 1
  properties:
    databases:
    - name: *atc_db
      # make up a role and password
      role: admin
      password: password
- name: worker
  label: Workers
  templates:
  - name: groundcrew
    release: concourse
  - name: baggageclaim
    release: concourse
  - name: garden-runc
    release: concourse
  memory: 16384
  ephemeral_disk: 32768
  cpu: 4
  static_ip: 0
  dynamic_ip: 1
  single_az_only: false
  singleton: false
  instances: 1
  properties:
    garden:
      listen_network: tcp
      listen_address: 0.0.0.0:7777
    #http_proxy_url: http://XX.XX.XX.XX:8080   # IF PROXY CONFIG FOR THE workers EXISTS, SETUP IT HERE. OTHERWISE REMOVE IT
    #https_proxy_url: http://XX.XX.XX.XX:8080  # IF PROXY CONFIG FOR THE workers EXISTS, SETUP IT HERE. OTHERWISE REMOVE IT
    #no_proxy: [localhost,127.0.0.1]           # IF PROXY CONFIG FOR THE workers EXISTS, you may add here a list domains and IPs with optional port for which the proxy should be bypassed
requires_product_versions:
- name: cf
  version: '~> 1.10'
```

**Comment by mboldt** [comment] 2017-06-12 15:21
Thank you for the extra context. I shuffled the `jobs` section underneath the `concourse` package (where it should be), and it worked as expected, i.e., I see:
```
...
- name: web
  ...
  manifest: |
    ...
    postgresql_database: atc
...
- name: db
  ...
  manifest: |
    databases:
    - name: atc
```
BOSH links is probably a better solution; glad you went in that direction. Since I can't reproduce the problem, and you've moved on, I will go ahead and close this issue.

**Closed as completed by mboldt** 2017-06-12 15:21 UTC

**Comment by mboldt** [comment] 2017-06-12 15:23
As an afterthought, the only thing that pops into my mind is that maybe you had an older version of the YAML library, and it didn't support anchors, or had a bug. I have no evidence for that, just seems like the next thing I would check.

**Comment by alexvasseur** [comment] 2017-06-12 16:17
You can precisely see that the alias has been handled by the generator so it won t be in the final bosh manifest (see concourse doc for example) - which will fail the bosh deploy

Envoyé de mon iPhone

**Comment by alexvasseur** [comment] 2017-06-12 16:44
I am running the tilegenerator in the docker image so I should not have any old libs right?

Envoyé de mon iPhone

**Comment by mboldt** [comment] 2017-06-15 17:08
Correct, the docker image should be fully up-to-date, so that was not the issue.

**Comment by PrasanthMohanCognizant** [comment] 2018-01-17 13:03
I'm trying to create a tile for concourse, which is similar to what you guys are discussing above. I'm running into some issues while trying to import the .pivotal file in PCF ops manager. Could you please let me know if there is something wrong with my tile.yml.


name: concourse-bosh # By convention lowercase with dashes
icon_file: /home/ubuntu/c.png
label: ConcourseBosh TestTile
description: Concourse-as-a-service

packages:
- name: concourse
  type: bosh-release
  path: https://bosh.io/d/github.com/concourse/concourse?v=3.0.1
  #path: /home/ubuntu/concourse-3.6.0.tgz
  version: 3.0.1
  #single_az_only: true
- name: garden-runc
  type: bosh-release
  path: https://bosh.io/d/github.com/cloudfoundry-incubator/garden-runc-release?v=1.0.0
  #path: /home/ubuntu/garden-runc-1.9.0.tgz
  version: 1.0.0
  #single_az_only: true

jobs:
- name: db
  label: PostgreSQL
  templates:
  - name: postgresql
    release: concourse
  memory: 4096
  ephemeral_disk: 8192
  persistent_disk: 32768
  cpu: 2
  static_ip: 0
  dynamic_ip: 1
  single_az_only: true
  singleton: true
  instances: 1
  properties:
    databases:
    - name: atc
      role: admin
      password: password

- name: web
  label: Concourse frontend
  templates:
  - name: atc
    release: concourse
  - name: tsa
    release: concourse
  memory: 4096
  ephemeral_disk: 8192
  cpu: 1
  static_ip: 1
  dynamic_ip: 0
  single_az_only: false
  singleton: false
  instances: 1
  properties:
    external_url: https://concourse.domain
    basic_auth_username: admin
    basic_auth_password: password
    tls_bind_port: 443
    postgresql_database: atc

- name: worker
  label: Workers
  templates:
  - name: groundcrew
    release: concourse
  - name: baggageclaim
    release: concourse
  - name: garden-runc
    release: concourse
  memory: 16384
  ephemeral_disk: 32768
  cpu: 4
  static_ip: 0
  dynamic_ip: 1
  single_az_only: false
  singleton: false
  instances: 1
  properties:
    garden:
      listen_network: tcp
      listen_address: 0.0.0.0:7777

requires_product_versions:
- name: cf
  version: '~> 1.10'

Note: I'm getting the following error in the ops manager and one other thing I noticed was the yml file generated inside the products/metadata doesn't look complete. Not sure if I'm missing something in the tile.yml or in the tile generation process.

NoMethodError
undefined method `any?' for nil:NilClass
/home/tempest-web/tempest/web/app/models/tempest/verifiers/internal/product_metadata_import_verifier.rb:26:in `missing_single_az_only?'
/home/tempest-web/tempest/web/app/models/tempest/verifiers/internal/product_metadata_import_verifier.rb:14:in `require_single_az_only_for_newer_versions'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/home/tempest-web/tempest/web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `block in simple'

**Comment by alexvasseur** [comment] 2018-01-17 22:29
You can direct message me thru git or email ? I could share a prototype tile that I have with you or if that is good for you have it on github and contribute together so that you update it from what I had?
